Add missing format specifier.
Pointed out by LLVM.

db_disasm.c:1018:13: error: format string is not a string literal (potentially insecure)

ok miod@